### ISSUE TITLE
Document new features on wiki

### ISSUE THREAD

**Issue by whnr** [whnr/dokuwiki-plugin-autonumbering#6]
Hi @jan-konczak-cs-put

Could you please document you merged PRs #4 and #5 on the plugins [wiki page](https://www.dokuwiki.org/plugin:autonumbering)?

I actually did not test the PRs since I don't use DW at the moment. They seemed reasonable. But I'm uncertain if the `Kung.Fu.#.#` case will actually render as `Kung Fu 1.1` as expected and works with the CSS highlighting. Please test that. Thank you.

**Comment by jan-konczak-cs-put** [comment]
> Could you please document you merged PRs #4 and #5 on the plugins [wiki page](https://www.dokuwiki.org/plugin:autonumbering)?

Sure, I've just done that.

> But I'm uncertain if the `Kung.Fu.#.#` case will actually render as `Kung Fu 1.1` as expected and works with the CSS highlighting. Please test that.

I did check if it's all fine before creating the PR ;-) You can see it live here:
https://www.cs.put.poznan.pl/jkonczak/os_cp:intro#getting_help
All the "Exercise <num>" texts use both of these features.
I tested also that `Kung.Fu.#.#` produces `Kung Fu 1.1`.

**Comment by whnr** [comment]
Thank you! Looks great!
